server:
  port: 9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: my-database
      username: vulcanson
      password: 1234